version: '2'
services:
  mysql:
    hostname: mysql
    image: mysql:5.7
    # network_mode: "host" # 如果需要容器使用宿主机IP(内网IP)，则可以配置此项
    container_name: mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
    restart: always # 设置容器自启模式
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置utf8字符集
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - MYSQL_ROOT_PASSWORD=root # 设置root密码
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - /home/james/data/mysql/data:/var/lib/mysql/data # 映射数据库保存目录到宿主机，防止数据丢失
      - /home/james/data/mysql/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件
    ports:
      - "3306:3306"

#  redis:
#    hostname: redis
#    image: redis:5.0.4
#    container_name: redis
#    restart: always
#    command: redis-server /etc/redis.conf # 启动redis命令
#    environment:
#      - TZ=Asia/Shanghai
#    volumes:
#      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
#      - redis_data:/data
#      - redis_cnf:/etc/redis.conf
#    ports:
#      - "6379:6379"
volumes:
  mysql_data:
  mysql_cnf:
#  redis_data:
#  redis_cnf: